In [2]:
import numpy as np

In [3]:
#creating arrays
a=np.array([1,2,3])
print("Array a:",a)
b=np.array([[1,2,3],[4,5,6]])
print("Array b:\n",b)

Array a: [1 2 3]
Array b:
 [[1 2 3]
 [4 5 6]]


In [4]:
#array indexing and slicing
print("First element of a: ",a[0])
print("First row of b:",b[0, :])

First element of a:  1
First row of b: [1 2 3]


In [5]:
#Array operations
c =a + 10
print("Array c: ",c)
d=b*2
print("Array d: \n",d)

Array c:  [11 12 13]
Array d: 
 [[ 2  4  6]
 [ 8 10 12]]


In [6]:
#Broadcasting
e=a*np.array([1,2,3])
print("Array e: ",e)

Array e:  [1 4 9]


In [7]:
#Advanced indexing
f=b[[0,1],[1,2]]
print(" Advanced indexing: ",f)

 Advanced indexing:  [2 6]


In [8]:
#Linear Algebra operations
g=np.dot(a,a)
print("Dot prodct g: ",e)

Dot prodct g:  [1 4 9]
